/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lnj.restaurant;

import java.awt.BorderLayout;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.*;

/**
 *
 * @author Josiane Mango
 */
public class Menu extends javax.swing.JFrame {
    
    private JFrame myframe;
    private JPanel mypanel;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josiane Mango\\Desktop\\imagesproject\\featured_drinks.jpg")); // NOI18N
        jButton2.setText("Drinks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(255, 255, 0));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josiane Mango\\Desktop\\imagesproject\\pexels-photo-103124.jpeg")); // NOI18N
        jButton4.setText("Breakfast");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josiane Mango\\Desktop\\imagesproject\\desserts.jpg")); // NOI18N
        jButton1.setText("desserts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(102, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josiane Mango\\Desktop\\imagesproject\\lunch1.jpg")); // NOI18N
        jButton3.setText("Lunch");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(255, 51, 204));
        jButton5.setText("Go Back to Book");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.sql.Connection con = null;
        Statement st = null;
        ResultSet rs=null;
        String s;
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost/restaurantlnj", "root", "");
        st = con.createStatement();
        s ="select Name,Price from drinks";
        rs = st.executeQuery(s);
        ResultSetMetaData rsmt = rs.getMetaData();
        int c = rsmt.getColumnCount ();
        Vector column = new Vector(c);
        for (int i=1; i<=c; i++)
        {
           column.add(rsmt.getColumnName(i)); 
        }
        Vector data = new Vector();
        Vector row= new Vector();
        while(rs.next())
        {
            row = new Vector(c);
            for(int i = 1; i <= c; i++){
                row.add(rs.getString(i));
            }
            data.add(row);
        }
        
        
       JFrame myframe= new JFrame ("Table from Database");
        myframe.setSize(900,600);
        myframe.setLocationRelativeTo(null);
        myframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel mypanel = new JPanel();
        
       JTable mytable = new JTable(data, column);
       
       JScrollPane jsp = new JScrollPane(mytable);
        
        mypanel.setLayout(new BorderLayout());
        mypanel.add(jsp, BorderLayout.CENTER);
        
        
        myframe.setContentPane(mypanel);
        myframe.setVisible(true);
        
        
        
        
        
        
    }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }finally{
            try {
                st.close();
                rs.close();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"ERROR ");
            }
            
           
                
            }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Customerdetails cd= new Customerdetails();
        cd.setVisible(true);
        cd.pack();
        cd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.sql.Connection con = null;
        Statement st = null;
        ResultSet rs=null;
        String s;
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost/restaurantlnj", "root", "");
        st = con.createStatement();
        s ="select Name, Price from lunch";
        rs = st.executeQuery(s);
        ResultSetMetaData rsmt = rs.getMetaData();
        int c = rsmt.getColumnCount ();
        Vector column = new Vector(c);
        for (int i=1; i<=c; i++)
        {
           column.add(rsmt.getColumnName(i)); 
        }
        Vector data = new Vector();
        Vector row= new Vector();
        while(rs.next())
        {
            row = new Vector(c);
            for(int i = 1; i <= c; i++){
                row.add(rs.getString(i));
            }
            data.add(row);
        }
        
        
       JFrame myframe= new JFrame ("Table from Database");
        myframe.setSize(900,600);
        myframe.setLocationRelativeTo(null);
        myframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel mypanel = new JPanel();
        
       JTable mytable = new JTable(data, column);
       
       JScrollPane jsp = new JScrollPane(mytable);
        
        mypanel.setLayout(new BorderLayout());
        mypanel.add(jsp, BorderLayout.CENTER);
        
        
        myframe.setContentPane(mypanel);
        myframe.setVisible(true);
        
        
        
        
        
        
    }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }finally{
            try {
                st.close();
                rs.close();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"ERROR ");
            }
            
           
                
            }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       java.sql.Connection con = null;
        Statement st = null;
        ResultSet rs=null;
        String s;
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost/restaurantlnj", "root", "");
        st = con.createStatement();
        s ="select Name,Price from breakfast";
        rs = st.executeQuery(s);
        ResultSetMetaData rsmt = rs.getMetaData();
        int c = rsmt.getColumnCount ();
        Vector column = new Vector(c);
        for (int i=1; i<=c; i++)
        {
           column.add(rsmt.getColumnName(i)); 
        }
        Vector data = new Vector();
        Vector row= new Vector();
        while(rs.next())
        {
            row = new Vector(c);
            for(int i = 1; i <= c; i++){
                row.add(rs.getString(i));
            }
            data.add(row);
        }
        
        
        JFrame myframe= new JFrame ("Table from Database");
        myframe.setSize(900,600);
        myframe.setLocationRelativeTo(null);
        myframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel mypanel = new JPanel();
        
       JTable mytable = new JTable(data, column);
       
       JScrollPane jsp = new JScrollPane(mytable);
        
        mypanel.setLayout(new BorderLayout());
        mypanel.add(jsp, BorderLayout.CENTER);
        
        
        myframe.setContentPane(mypanel);
        myframe.setVisible(true);
        
        
        
        
        
        
    }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }finally{
            try {
                st.close();
                rs.close();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"ERROR ");
            }
            
           
                
            }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.sql.Connection con = null;
        Statement st = null;
        ResultSet rs=null;
        String s;
        try{
        con= DriverManager.getConnection("jdbc:mysql://localhost/restaurantlnj", "root", "");
        st = con.createStatement();
        s ="select Name,Price from desserts";
        rs = st.executeQuery(s);
        ResultSetMetaData rsmt = rs.getMetaData();
        int c = rsmt.getColumnCount ();
        Vector column = new Vector(c);
        for (int i=1; i<=c; i++)
        {
           column.add(rsmt.getColumnName(i)); 
        }
        Vector data = new Vector();
        Vector row= new Vector();
        while(rs.next())
        {
            row = new Vector(c);
            for(int i = 1; i <= c; i++){
                row.add(rs.getString(i));
            }
            data.add(row);
        }
        
        
       JFrame myframe= new JFrame ("Table from Database");
        myframe.setSize(900,600);
        myframe.setLocationRelativeTo(null);
        myframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel mypanel = new JPanel();
        
       JTable mytable = new JTable(data, column);
       
       JScrollPane jsp = new JScrollPane(mytable);
        
        mypanel.setLayout(new BorderLayout());
        mypanel.add(jsp, BorderLayout.CENTER);
        
        
        myframe.setContentPane(mypanel);
        myframe.setVisible(true);
        
        
        
        
        
        
    }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "ERROR");
            
        }finally{
            try {
                st.close();
                rs.close();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"ERROR ");
            }
            
           
                
            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
